### ISSUE TITLE
Инстансы для счетчиков

### ISSUE THREAD

**Issue by fearrr** [alexusmai/yandex-metrika#4]
Скажите планируете ли развивать проект?
Есть предложения добавить инстансы для использования нескольких счетчиков, это может быть полезно для мультидоменных проектов, на данный момент такой функционал я не обнаружил.

**Comment by alexusmai** [comment]
По идее и сейчас можно получать данные с других счетчиков, если конечно они все входят в ваш аккаунт яндекс метрики, под который выдан токен. 
Например можно использовать - Произвольный запрос к Api Yandex Metrika, там можно указать id другого счетчика, но сам запрос к статистике придется уже прописывать ручками.. это конечно не очень удобно.
По развитию пока планов нет, да и времени тоже, может как появится посмотрю, что можно сделать.
