### ISSUE TITLE
Цели

### ISSUE THREAD

**Issue by i-prikot** [alexusmai/yandex-metrika#9]
Доброго дня.

Можно ли получить список целей и конверсию по ним за период?

**Comment by alexusmai** [comment]
Добрый день.
К сожалению не могу точно ответить на этот вопрос, но думаю, что можно. 

Вам нужен этот пункт - [docs](https://github.com/alexusmai/yandex-metrika#%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81-%D0%BA-api-yandex-metrika)
И ищите в документации Yandex-а как составить правильно нужные вам запросы - [yandex docs](https://yandex.ru/dev/metrika/)
